### ISSUE TITLE
5.7.x for alpine

### ISSUE THREAD

**Issue by jmordica** [kamailio/kamailio-ci#10]
Are there any plans to support minor 5.7.x versions? Like 5.7.3?

Thanks!

**Comment by linuxmaniac** [comment]
Well, the support is there but the README is not updated
```
docker pull ghcr.io/kamailio/kamailio-ci:5.7.4-alpine
```
See https://github.com/kamailio/kamailio-ci/pkgs/container/kamailio-ci/versions
