### ISSUE TITLE
apk not found / kamailio-redis module

### ISSUE THREAD

**Issue by felipem1210** [kamailio/kamailio-ci#2]
Hi, I'm trying to install the module kamailio-redis in the master image and I can't because i'm getting: "apk: not found". Can you add the kamailio-redis module ?

**Comment by sergey-safarov** [comment]
you can try
```sh
[safarov@safarov-dell src]$ docker run -it --entrypoint=sh kamailio/kamailio-ci:master-alpine
/ # find / -name "*redis*"
/usr/lib/kamailio/modules/ndb_redis.so
/usr/lib/kamailio/modules/topos_redis.so
/usr/lib/libhiredis.so.0.14
```
apk utility present in images `-alpine` and `-alpine.debug`.

**Comment by felipem1210** [comment]
Hi,
The module I'm needing is db_redis, that is not present in the master-alpine image, so what I do is that
I see is available in apk package kamailio-redis: https://pkgs.alpinelinux.org/packages?name=kamailio&branch=edge

The problem is that there is a version mismatch between this module and kamailio pre installed in image so it makes other modules crash

 0(1) ERROR: <core> [core/sr_module.c:347]: version_control(): module version mismatch for /usr/lib/kamailio/modules/usrloc.so; core: kamailio 5.2.2 (x86_64/linux); module: kamailio 5.3.0-dev5 (x86_64/linux)

That's why I'm asking if you can add the module db_redis in the master-alpine image

Thanks

**Comment by sergey-safarov** [comment]
I pushed commits to `master` and `5.2` branches.
Docker image for master you can test now. For 5.2 you can test after hour.
If still issue you can reopen.

**Comment by felipem1210** [comment]
Thank you so much!!
