### ISSUE TITLE
'mysql' tool not found: set MYSQL variable to correct tool path

### ISSUE THREAD

**Issue by hvspa** [kamailio/kamailio-ci#3]
hi Victor,

I'd like to thank you for maintaining kamailio docker containers on the docker hub. I tried to use ci:5.1.10 build and ran into an error while trying to execute kamctl command (https://hub.docker.com/r/kamailio/kamailio-ci):

[root@host ~]# docker exec -i -t kamailio /usr/sbin/kamctl stop
error: 'mysql' tool not found: set MYSQL variable to correct tool path

i am using following image:

CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS              PORTS               NAMES
52316450e804        kamailio/kamailio-ci:5.1.10   "kamailio -DD -E"   7 hours ago         Up 7 hours                              kamailio

Do you think it is somehow possible to include mysql in 5.1.10 build?  

thanks in advance,

**Comment by sergey-safarov** [comment]
Hi @hvspa 
Sorry for the long answer.
You can modify the base container with `apk` support.
Create `dockerfile` with content like.
```
FROM kamailio/kamailio-ci:5.3-alpine

RUN apk --no-cache add mariadb-client
```
And then execute command like
```sh
docker build -t mykamailio .
```
After you can use modified `kamailio` image with required tools.

**Comment by sergey-safarov** [comment]
I think issue is resolved.
I close the ticket.

**Comment by hvspa** [comment]
> apk --no-cache add mariadb-client

thanks Sergey, 

i am trying to install maria db client in existing running container, as it is prod now. any ways to do it?

```
/ # apk --no-cache add mariadb-client
sh: apk: not found
/ # 
```

thanks

**Comment by sergey-safarov** [comment]
You need to use `kamailio/kamailio-ci:5.1.10-alpine` image as base.
This image has the same Kamailio binaries with all alpine tools like apk.

**Comment by hvspa** [comment]
> You need to use `kamailio/kamailio-ci:5.1.10-alpine` image as base.
> This image has the same Kamailio binaries with all alpine tools like apk.

agreed, but it is not alpine, it is busybox:

/ # busybox | head -1
BusyBox v1.31.1 () multi-call binary.
/ # 

i have no much experience with busy box and google did not reveal any trivial install guides..

thanks in advance,
