### ISSUE TITLE
Module app_lua_sr not installed in image.

### ISSUE THREAD

**Issue by mkl262** [kamailio/kamailio-ci#5]
Hi,

The `app_lua_sr` module isn't installed in the image.
I know it has a depreciation notice, but I didn't see its EOL.
Is there a way to install it?

Thanks.

**Comment by sergey-safarov** [comment]
Which packages do you use?

**Comment by mkl262** [comment]
I use the kamailio:kamailio-ci:5.4.2 image

**Comment by sergey-safarov** [comment]
Looks as need add `luajit-dev` package into the builder and maybe add some packaging rules.

**Comment by miconda** [comment]
`luajit-dev` should not be the default requirement for app_lua* modules, but the alternative to `liblua-dev`.

**Comment by sergey-safarov** [comment]
As I see if not defined `LUAJIT` build flag, then searched `luajit` headers files.
If headers files not found, then `app_lua_sr` module not compiled.

https://github.com/kamailio/kamailio/blob/master/src/modules/app_lua_sr/Makefile#L103-L104

**Comment by sergey-safarov** [comment]
Maybe I not properly understand Makefile.
Anyway I will try build with and without `luajit` headers.

**Comment by sergey-safarov** [comment]
`app_lua_sr` module packaged by commit 
https://github.com/kamailio/kamailio/commit/6782b2c1789f162b405ec0b9894f61075a4307f9

And then backported to `5.4` and `5.3` branches.

**Comment by mkl262** [comment]
Thanks!
