### ISSUE TITLE
lwsc module

### ISSUE THREAD

**Issue by jmordica** [kamailio/kamailio-ci#7]
Are you able to include the `lwsc` module support? Adding `libwebsockets` is required for this module.

**Comment by sergey-safarov** [comment]
Related commits added to the Kamailio master branch.
Expecting tomorrow will be ready daily image build.
If all is fine, then I will backport to a stable branch.

**Comment by jmordica** [comment]
Awesome!!

**Comment by sergey-safarov** [comment]
Packaging backported into `5.7` and `5.6` branches.
Expecting module will be present in the release image too.
If not, please reopen.
